version: '3'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "21017:27017"

  backend:
    build: ./backend
    container_name: springboot-studentservice
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: react-studentservice
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
